mano_adjustments:
  - [0, 0, 0]
  - [0, 0, 0]
  - [0, 0, 0]
  - [0, 0, 0]
  - [0, 0, 0]
  - [0, 0, 0]
  - [0, 0, 0]
  - [0, 0, 0]
  - [0, 0, 0]
  - [0, 0, 0]
  - [0, 0, 0]
  - [0, 0, 0]
  - [0, 0, 0]
  - [0, 0, 0]
  - [0, 0, 0]
  - [0, 0, 0]

lr: 0.01
use_scalar_distance_palm: false
loss_coeffs: [5.0, 5.0, 5.0, 5.0, 5.0]
joint_regularizers: []
